config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true, length:{minimum: 3}
    validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.html
            format.json {render json: @kittens}
        end
    end

    def new
        @kitten = Kitten.new
    end

    def show
        @kitten = Kitten.find(params[:id])
    end

    def create
        @kitten = Kitten.new(kitten_params)

        if @kitten.save
            flash[:success] = "kitten created successfuly"
            # redirect_to kitten_path(@kitten.id)
            redirect_to kittens_path, notice: "object was successfully created."
        else
            flash.now[:error] = "something went wrong. Please try again."
            render :new, status: :unprocessable_entity
        end
    end

    # def create
    #     @kitten = Kitten.new(kitten_params)
      
    #     if @kitten.save
    #       flash[:success] = "Kitten created successfully"
    #       render turbo_stream: turbo_stream.replace(@kitten, partial: "kittens/kitten", locals: { kitten: @kitten })
    #     else
    #       flash.now[:error] = "Something went wrong. Please try again."
    #       render :new, status: :unprocessable_entity
    #     end
    # end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])

        if @kitten.update(kitten_params)
            flash[:success] = "User updated successfully."
            redirect_to @kitten#kitten_path(@kitten.id)
        else
            flash.now[:error] = "Couldn't update kitten."
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy

        redirect_to root_path, notice: "kitten deleted successfully."
    end

    private

    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness);
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten, local:true) do |form|%>
    
    <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this object from being saved:</h2>
      <ul>
      <% @kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :name, "Name: "%>
    <%= form.text_field :name%>

    <%= form.label :age, "Age: "%>
    <%= form.text_field :age%>

    <%= form.label :cuteness ,"Cuteness: "%>
    <%= form.text_field :cuteness%>

    <%= form.label :softness, "Softness: "%>
    <%= form.text_field :softness%>

    <%= form.submit%>
<% end %>

app/views/kittens/edit.html.erb
<h3>Edit kitten Details</h3>

<% if @kitten.errors.full_messages %>

    <% @kitten.errors.full_messages.each do |error|%>
        <%= error %>
    <% end %>
  
<% end %>

<%= render "form", locals: {kitten: @kitten}%>
<br>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<hr> <br>

<%@kittens.each do |kitten|%>
    <%= link_to "KittenId:#{kitten.id}", kitten_path(kitten.id) %>

    <%= kitten.name %>
    <%= kitten.age %>
    <%= kitten.cuteness %>
    <%= kitten.softness %>

    <br><hr>
<% end %>

<%= link_to 'Add Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h3>Create new Kitten</h3>

<%= render "form", locals: {kitten: @kitten}%>

app/views/kittens/show.html.erb
<h1>@kitten <%= @kitten.name%></h1>

<span>Name: <%= @kitten.name %> </span><hr>
<span>Age: <%= @kitten.age %> </span> <hr>
<span>Cuteness: <%= @kitten.cuteness %> </span> <hr>
<span>Softness: <%= @kitten.softness %> </span> <hr>

<%= link_to 'Edit this kitten details', edit_kitten_path(@kitten.id) %>
<hr>
<%= link_to 'Delete this Kitten', kitten_path(@kitten.id), data:{"turbo-method": :delete}%>
<hr>
<%= link_to 'Back to Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://matcha.mizu.sh/matcha.css">
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    
    <%= yield %>
  
  </body>
</html>